---
- name: Customization Linux Ultramarine
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    user_name: patryk

#  tasks:
 #   - name: Create user {{ user_name }}
  #    user:
   #     name: "{{ user_name }}"
    #    state: present
     #   shell: /bin/bash

   # - name: Add user {{ user_name }} to wheel group
    #  user:
     #   name: "{{ user_name }}"
      #  groups: wheel
       # append: yes

  roles:
    - role: packages
    - role: vscode
    - role: docker
    - role: brave
    - role: system
      vars:
        user_name: "{{ user_name }}"
    - role: gnome
      vars:
        user_name: "{{ user_name }}"
    - role: tmux
      vars:
        user_name: "{{ user_name }}"


