---
- name: Add Brave repo
  command:
    cmd: dnf config-manager --add-repo=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo

- name: Import Brave key
  command:
    cmd: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: Install Brave Browser and its keyring
  dnf:
    name:
      - brave-browser
      - brave-keyring
    state: present

- name: Set Brave as default browser
  command:
    cmd: xdg-settings set default-web-browser brave-browser.desktop
