---
- name: Adding Docker repo
  command:
    cmd: dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo

- name: Installation Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enabling docker service
  systemd:
    name: docker
    enabled: yes
    state: started
