---
- name: GET UID {{ user_name }}
  command: id -u {{ user_name }}
  register: user_uid_result
  changed_when: false

- set_fact:
    user_uid: "{{ user_uid_result.stdout }}"

- name: Clone Oh my tmux! repository
  git:
    repo: 'https://github.com/gpakosz/.tmux.git'
    dest: "/home/{{ user_name }}/.tmux"
    update: yes
  become: yes
  become_user: "{{ user_name }}"

- name: Create symbolic link for .tmux.conf
  command:
    cmd: ln -s -f .tmux/.tmux.conf
    chdir: "/home/{{ user_name }}/"
  become: yes
  become_user: "{{ user_name }}"

- name: Copy .tmux.conf.local to home directory
  copy:
    src: "/home/{{ user_name }}/.tmux/.tmux.conf.local"
    dest: "/home/{{ user_name }}/.tmux.conf.local ."
    remote_src: yes
  become: yes
  become_user: "{{ user_name }}"

